version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 493339161712.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=493339161712.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics

  build:
    commands:
      - echo Building the Docker image...
      - cd analytics
      - docker build -t coworking-analytics .
      - docker tag coworking-analytics:latest $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
